// Generated by TMBtools: do not edit by hand

#define TMB_LIB_INIT R_init_stockseasonr_TMBExports
#include <TMB.hpp>
#include "nb_dirchlet_1re.hpp"

template<class Type>
Type objective_function<Type>::operator() () {
  DATA_STRING(model);
  if (model == "nb_dirchlet_1re") {
    return nb_dirchlet_1re(this);
  } else {
    error("Unknown model.");
  }
  return 0;
}
