#' Stock-specific abundance plot
#'
#' @param comp_dat Composition dataframe; each row represents a sampling event 
#'   (e.g. genetic samples collected from a given day and region)
#' @param pred_dat_comp Dataframe of fixed effects composition predictions (i.e.
#'   months and regions); generated using stockseasonr::gen_tmb()
#' @param mod_fit Parameter estimates generated by TMB::sdreport() and returned
#'   by stockseasonr::fit_stockseason()
#'
#' @return
#' Ribbon plot representing fixed effects predictions of seasonal trends in 
#'   stock-specific abundance, faceted by stock, with 95% confidence intervals.
#' @export
#' 
#' @importFrom dplyr select distinct filter arrange mutate row_number mutate_if
#' @importFrom ggplot2 ggplot aes geom_line geom_ribbon scale_fill_brewer 
#' @importFrom ggplot2 scale_colour_brewer labs theme scale_x_continuous 
#' @importFrom ggplot2 facet_wrap coord_cartesian element_text unit 
#' @importFrom ggplot2 theme_classic
#'
#' @examples
#' in1 <- gen_tmb(comp_dat = comp_ex, catch_dat = catch_ex, 
#'                model_type = "integrated")
#' # model fitting will take several seconds
#' m1 <- fit_stockseason(comp_dat = comp_ex, catch_dat = catch_ex, 
#'                       model_type = "integrated")
#' plot_ribbon_abund(comp_dat = comp_ex, pred_dat_comp = in1$pred_dat_comp,
#'                   mod_fit = m1)
#' 

plot_ribbon_abund <- function(comp_dat, pred_dat_comp, mod_fit) {
  
  # summarize predictions
  ssdr <- summary(mod_fit)
  comp_abund_pred <- ssdr[rownames(ssdr) %in% "log_pred_abund_mg", ]
  stk_names <- unique(comp_dat$agg)
  dum <- purrr::map_dfr(seq_along(stk_names), ~ pred_dat_comp)
  
  # generate plotting dataframe
  dum2 <- data.frame(
    stock = as.character(rep(stk_names, each = nrow(pred_dat_comp))),
    link_abund_est = comp_abund_pred[ , "Estimate"],
    link_abund_se =  comp_abund_pred[ , "Std. Error"]
  ) %>% 
    cbind(dum, .) %>%
    mutate(
      comp_abund_est = exp(link_abund_est),
      comp_abund_low = exp(link_abund_est + (qnorm(0.025) * link_abund_se)),
      comp_abund_up = exp(link_abund_est + (qnorm(0.975) * link_abund_se))
    ) 
  
  ggplot(data = dum2, aes(x = month_n)) +
    geom_line(aes(y = comp_abund_est, colour = region)) +
    geom_ribbon(aes(ymin = comp_abund_low, ymax = comp_abund_up, 
                    fill = region), 
                alpha = 0.5) +
    scale_fill_brewer(name = "Region", palette = "Dark2") +
    scale_colour_brewer(name = "Region", palette = "Dark2") +
    labs(y = "Predicted Catch", x = "Month") +
    facet_wrap(~ stock, scales = "free_y") +
    theme_classic() +
    theme(legend.position = "top",
          axis.text = element_text(size=9),
          plot.margin = unit(c(5.5, 10.5, 5.5, 5.5), "points")) +
    scale_x_continuous(breaks = seq(min(dum2$month_n), max(dum2$month_n), 
                                    by = 2)) +
    coord_cartesian(expand = FALSE, ylim = c(0, NA))
}
