#' Stacked composition plot
#'
#' @param x_var Explanatory variable within pred_dat to be plotted on x-axis 
#'   (must be continuous). 
#' @param grouping_var Character or factor variable within pred_dat that
#'   was used to generate composition estimates.
#' @param facet_var Optional character or factor variable within pred_dat 
#'   corresponding to categorical main effects in fitted model.
#' @param ssdr Parameter estimates generated by 
#'   stockseasonr::fit_stockseasonr()$ssdr.
#' @param comp_dat Composition dataframe; each row represents a sampling event 
#'   (e.g. genetic samples collected from a given day and region)
#' @param pred_dat Dataframe of fixed effects composition predictions
#'
#' @return
#' Stacked ribbon plot representing trends in mean composition with optional 
#'   facets.
#' @export
#' 
#' @importFrom dplyr mutate 
#' @importFrom ggplot2 ggplot aes aes_string geom_area scale_fill_brewer 
#' @importFrom ggplot2 scale_colour_brewer labs theme scale_x_continuous 
#' @importFrom ggplot2 facet_wrap coord_cartesian element_text unit
#' @importFrom ggplot2 theme_classic 
#'
#' @examples
#' dum_pred <- expand.grid(
#'   month_n = seq(1, 12, by = 0.1),
#'   region = unique(comp_ex$region)
#' )
#' # model fitting will take several seconds
#' m1 <- fit_stockseasonr(
#'   comp_formula = agg ~ 1 + region + 
#'     s(month_n, bs = "tp", k = 4, m = 2) + 
#'     (1 | year),
#'   comp_dat = comp_ex,
#'   pred_dat = dum_pred,
#'   model = "dirichlet",
#'   random_walk = TRUE,
#'   fit = TRUE,
#'   nlminb_loops = 2, newton_loops = 1
#' )
#' plot_stacked_comp(x_var = "month_n", grouping_var = "agg", 
#'                   facet_var = "region", ssdr = m1$ssdr, comp_dat = comp_ex,
#'                   pred_dat = dum_pred)
#' 

plot_stacked_comp <- function(x_var, grouping_var, facet_var = NULL,
                              ssdr, comp_dat, pred_dat) {
  
  if (!is.numeric(pred_dat[[x_var]])) {
    stop("Explanatory variable is not continuous. Stacked ribbon plot is not
         appropriate.")
  }
  
  comp_pred <- ssdr[rownames(ssdr) %in% "logit_pred_Pi_prop", ]
  group_names <- unique(comp_dat[[grouping_var]])
  dum <- purrr::map_dfr(seq_along(group_names), ~ pred_dat)
  
  dum2 <- data.frame(
    group = as.character(rep(group_names, each = nrow(pred_dat))),
    link_prob_est = comp_pred[ , "Estimate"],
    link_prob_se =  comp_pred[ , "Std. Error"]
  ) %>% 
    cbind(dum, .) %>%
    mutate(
      pred_prob_est = plogis(link_prob_est),
      pred_prob_low = plogis(link_prob_est + (qnorm(0.025) * link_prob_se)),
      pred_prob_up = plogis(link_prob_est + (qnorm(0.975) * link_prob_se))
    ) 
  
  p <- ggplot(data = dum2, aes_string(x = x_var)) +
    geom_area(aes_string(y = "pred_prob_est", colour = "group", fill = "group"), 
              stat = "identity") +
    scale_fill_brewer(name = "Group", palette = "Spectral") +
    scale_colour_brewer(name = "Group", palette = "Spectral") +
    labs(y = "Predicted Composition") +
    theme_classic() +
    theme(legend.position = "right",
          axis.text = element_text(size=9),
          plot.margin = unit(c(2.5, 11.5, 5.5, 5.5), "points")
    ) +
    coord_cartesian(expand = FALSE, ylim = c(0, NA))
  
  if(!is.null(facet_var)) {
    p <- p +
      facet_wrap(stats::as.formula(paste("~", facet_var)))
  }
  
  return(p)
}
