#' Stacked composition plot
#'
#' @param comp_dat Composition dataframe; each row represents a sampling event 
#'   (e.g. genetic samples collected from a given day and region)
#' @param pred_dat_comp Dataframe of fixed effects composition predictions (i.e.
#'   months and regions); generated using stockseasonr::gen_tmb()
#' @param mod_fit Parameter estimates generated by TMB::sdreport() and returned
#'   by stockseasonr::fit_stockseason()
#'
#' @return
#' Stacked ribbon plot representing seasonal trends in mean stock composition 
#'   and faceted by catch region.
#' @export
#' 
#' @importFrom dplyr select distinct filter arrange mutate row_number mutate_if
#' @importFrom ggplot2 ggplot aes geom_area scale_fill_brewer 
#' @importFrom ggplot2 scale_colour_brewer labs theme scale_x_continuous 
#' @importFrom ggplot2 facet_wrap coord_cartesian element_text unit
#' @importFrom ggplot2 theme_classic
#'
#' @examples
#' in1 <- gen_tmb(comp_dat = comp_ex, model_type = "composition")
#' # model fitting will take several seconds
#' m1 <- fit_stockseason(comp_dat = comp_ex, model_type = "composition")
#' plot_stacked_comp(comp_dat = comp_ex, pred_dat_comp = in1$pred_dat_comp,
#'                   mod_fit = m1)
#' 

plot_stacked_comp <- function(comp_dat, pred_dat_comp, mod_fit) {
  
  # summarize predictions
  ssdr <- summary(mod_fit)
  comp_pred <- ssdr[rownames(ssdr) %in% "logit_pred_pi_prop", ]
  stk_names <- unique(comp_dat$agg)
  dum <- purrr::map_dfr(seq_along(stk_names), ~ pred_dat_comp)
  
  # generate plotting dataframe
  dum2 <- data.frame(
    stock = as.character(rep(stk_names, each = nrow(pred_dat_comp))),
    link_prob_est = comp_pred[ , "Estimate"],
    link_prob_se =  comp_pred[ , "Std. Error"]
  ) %>% 
    cbind(dum, .) %>%
    mutate(
      pred_prob_est = plogis(link_prob_est),
      pred_prob_low = plogis(link_prob_est + (qnorm(0.025) * link_prob_se)),
      pred_prob_up = plogis(link_prob_est + (qnorm(0.975) * link_prob_se))
    ) 
  
  #generate plot
  ggplot(data = dum2, aes(x = month_n)) +
    geom_area(aes(y = pred_prob_est, colour = stock, fill = stock), 
              stat = "identity") +
    scale_fill_brewer(name = "Stock", palette = "Spectral") +
    scale_colour_brewer(name = "Stock", palette = "Spectral") +
    labs(y = "Predicted Stock Composition", x = "Month") +
    theme_classic() +
    theme(legend.position = "right",
          axis.text = element_text(size=9),
          plot.margin = unit(c(2.5, 11.5, 5.5, 5.5), "points")
    ) +
    scale_x_continuous(breaks = seq(min(dum2$month_n), max(dum2$month_n), 
                                    by = 2)) +
    facet_wrap(~region) +
    coord_cartesian(expand = FALSE, ylim = c(0, NA))
}
